### ISSUE TITLE
cannot build, always uses --legacy

### ISSUE THREAD

**Issue by ldelossa** [truewebartisans/actions-sapper#1]
I'm having trouble with this, as it always seems to use --legacy

```

11s
> Legacy builds are not supported for projects using webpack
Run truewebartisans/actions-sapper@master
/usr/bin/docker run --name d3d03c9804e0754607b3479e695eaf7a90_653252 --label 3888d3 --workdir /github/workspace --rm -e INPUT_BUILD_MODE -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/ldelossa-blog/ldelossa-blog":"/github/workspace" 3888d3:d03c9804e0754607b3479e695eaf7a90 --legacy
Running `npm install`
npm WARN TODO@0.0.1 No repository field.
npm WARN TODO@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 439 packages from 263 contributors and audited 510 packages in 7.684s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Build Sapper
> Building...
> Legacy builds are not supported for projects using webpack
```

I removed it from the workflow file:

```
name: Build Sapper and Deploy to GitHub Pages

on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build Sapper
        uses: truewebartisans/actions-sapper@master
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: __sapper__/export
          publish_branch: gh-pages
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          args: "--entry about"
```
